### PR TITLE
Make text < 1.3 instead of 1.2

### PR DESCRIPTION
**Pull request by k-bx**
Please make a release afterwards :) Thanks!

### CODE REVIEW

**Comment by k-bx** [comment]
@jfischoff hi! Could you please make a hackage release of file-command-qq with this change? Since that was the main intent, basically. Thanks!

**Comment by jfischoff** [comment]
I should be able to do it tomorrow. I just moved across the country so I have been busy.

**Comment by jfischoff** [comment]
Done

**Comment by k-bx** [comment]
Thank you!

**Pull request merged**
